In [3]:
import pandas as pd
from sqlalchemy import create_engine

#Update with credentials
engine = create_engine(
     "postgresql://postgres:sujal@localhost:5432/Superstore"
)

df = pd.read_sql("SELECT * FROM superstore", engine)

print(df.head())

   row_id        order_id  order_date   ship_date       ship_mode customer_id  \
0       1  CA-2017-152156  2017-08-11  2017-11-11    Second Class    CG-12520
1       2  CA-2017-152156  2017-08-11  2017-11-11    Second Class    CG-12520
2       3  CA-2017-138688  2017-12-06  2017-06-16    Second Class    DV-13045
3       4  US-2016-108966  2016-11-10  2016-10-18  Standard Class    SO-20335
4       5  US-2016-108966  2016-11-10  2016-10-18  Standard Class    SO-20335

     customer_name    segment        country             city       state  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   postal_code region       product_id         category sub_category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        product_name   sales
0                  Bush Somerset Collection Bookcase  261.96
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.94
2  Self-Adhesive Address Labels for Typewriters b...   14.62
3      Bretford CR4500 Series Slim Rectangular Table  957.58
4                     Eldon Fold 'N Roll Cart System   22.37

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9800 non-null   int64
 1   order_id       9800 non-null   object
 2   order_date     9800 non-null   object
 3   ship_date      9800 non-null   object
 4   ship_mode      9800 non-null   object
 5   customer_id    9800 non-null   object
 6   customer_name  9800 non-null   object
 7   segment        9800 non-null   object
 8   country        9800 non-null   object
 9   city           9800 non-null   object
 10  state          9800 non-null   object
 11  postal_code    9789 non-null   float64
 12  region         9800 non-null   object
 13  product_id     9800 non-null   object
 14  category       9800 non-null   object
 15  sub_category   9800 non-null   object
 16  product_name   9800 non-null   object
 17  sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

change the dtype of order_date and ship_date into datetime

In [5]:
#Changing the data dype 
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9800 non-null   int64
 1   order_id       9800 non-null   object
 2   order_date     9800 non-null   datetime64[ns]
 3   ship_date      9800 non-null   datetime64[ns]
 4   ship_mode      9800 non-null   object
 5   customer_id    9800 non-null   object
 6   customer_name  9800 non-null   object
 7   segment        9800 non-null   object
 8   country        9800 non-null   object
 9   city           9800 non-null   object
 10  state          9800 non-null   object
 11  postal_code    9789 non-null   float64
 12  region         9800 non-null   object
 13  product_id     9800 non-null   object
 14  category       9800 non-null   object
 15  sub_category   9800 non-null   object
 16  product_name   9800 non-null   object
 17  sales          9800 non-null   float64
 18  shipping_days  9800 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(2), object(13)
memory usage: 1.4+ MB

In [13]:
#Shipping delay per order
df['shipping_days'] = (df['ship_date'] - df['order_date']).dt.days

In [7]:
#Null per column

df.isnull().sum()

row_id            0
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_id       0
customer_name     0
segment           0
country           0
city              0
state             0
postal_code      11
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
dtype: int64

In [8]:
#Duplicated values
df.duplicated().sum()

np.int64(0)

In [15]:
#Stataical Summary of numeric column check 
df.describe()

,row_id,order_date,ship_date,postal_code,sales,shipping_days
count,9800.000000,9800,9800,9789.000000,9800.000000,9800.000000
mean,4900.500000,2017-04-12 14:24:35.265306112,2017-04-21 19:45:12.489796096,55273.322403,230.769079,9.222653
min,1.000000,2015-01-02 00:00:00,2015-01-04 00:00:00,1040.000000,0.440000,-321.000000
25%,2450.750000,2016-05-02 12:00:00,2016-05-08 00:00:00,23223.000000,17.250000,2.000000
50%,4900.500000,2017-05-30 00:00:00,2017-06-12 00:00:00,58103.000000,54.490000,4.000000
75%,7350.250000,2018-04-11 00:00:00,2018-05-02 00:00:00,90008.000000,210.605000,61.000000
max,9800.000000,2018-12-30 00:00:00,2019-05-01 00:00:00,99301.000000,22638.480000,214.000000
std,2829.160653,NaN,NaN,32041.223413,626.651906,95.447543

In [17]:
#Checking the outlier 
#Top 10 highest single line sales
df.nlargest(10,'sales')[['order_id','customer_name','category','sub_category','sales','shipping_days']]

,order_id,customer_name,category,sub_category,sales,shipping_days
2700,CA-2015-145317,Sean Miller,Technology,Machines,22638.48,5
6829,CA-2017-118689,Tamara Chand,Technology,Copiers,17499.95,212
8155,CA-2018-140151,Raymond Buch,Technology,Copiers,13999.96,2
2626,CA-2018-127180,Tom Ashbrook,Technology,Copiers,11199.97,2
4193,CA-2018-166709,Hunter Lopez,Technology,Copiers,10499.97,5
9041,CA-2017-117121,Adrian Barton,Office Supplies,Binders,9892.74,4
4101,CA-2015-116904,Sanjit Chand,Office Supplies,Binders,9449.95,5
4280,US-2017-107440,Bill Shonely,Technology,Machines,9099.93,4
8490,CA-2017-158841,Sanjit Engle,Technology,Machines,8749.95,59
6428,CA-2017-143714,Christopher Conant,Technology,Copiers,8399.98,4

In [18]:
#Avergae shiping time by ship mode
shipping_summary = df.groupby('ship_mode')['shipping_days'].agg(['mean','min','max','count']).round(1)
shipping_summary

                mean  min  max  count
ship_mode
First Class      6.6 -320   92   1501
Same Day         0.6  -87   31    538
Second Class     4.7 -321  153   1902
Standard Class  12.2 -320  214   5859